import type { Config } from "tailwindcss";

const config: Config = {
  
  content: [
    "./src/pages/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/components/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/app/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  theme: {
     fontFamily: {
      syne: ['Syne', 'sans-serif'],
      inter: ['Inter', 'sans-serif'],
    },
    screens: {
      '2xl': {'min': '1535px'},
      'xl': {'min': '1279px'},
      'lg': {'min': "800", "max": '1323px'},
      'md': {'min': '767px', 'max': '1100px'},
      'sm': {'min': '400px','max': '866px'},
    },
    extend: {
      boxShadow: {
        "button": "10px 16px 40px 0 rgb(255 84 117 / 46%)"
      },
      padding: {
        "clamp": "clamp(50px, 30vh, 100px) 0"
      },
      gridTemplateColumns: {
        "2.5": "1.25fr 1fr"
      },
      colors: {
        "--yellow": "#d0b20b",
        "--purple": "#400578",
      },
      fontFamily: {
        "AWConquerorDidotLight": ["AW-Conqueror-Didot-Light", "serif"],
        "AdventPro": ['Advent Pro', "sans-serif"], 
        "AbrilFatface": ["Abril Fatface", "sans-serif"],
        "Afacad": ["Afacad", "sans-serif"],
        "AlegreyaSans" : ['Alegreya Sans', "sans-serif"],
        "Anton": ['Anton', 'sans-serif'],
        "BebasNeue": ['Bebas Neue', 'sans-serif'],
        "Belanosima": ['Belanosima', 'sans-serif'],
        "BodoniModa": ['Bodoni Moda', 'serif'],
        "BubbleGum": ['Bubblegum Sans', 'cursive'],
        "Catalogue": ["Catalogue", "sans-serif"],
        "DomaineDisplayNarrowRegular": ["Domaine Display Narrow Regular", "Georgia","serif"],
        "DomaineDisplayNarrowRegularItalic": ["Domaine Display Narrow RegularItalic", "Georgia","serif"],
        "DomaineDisplayNarrowMedium": ["Domaine Display Narrow Medium", "Georgia","serif"],
        "DomaineDisplayNarrowMediumItalic": ["Domaine Display Narrow MediumItalic", "Georgia","serif"],
        "DomaineDisplayNarrowBold": ["Domaine Display Narrow Bold", "Georgia","serif"],
        "DomaineDisplayNarrowBoldItalic": ["Domaine Display Narrow BoldItalic", "Georgia","serif"],
        "DarkerGrotesque": ['Darker Grotesque', 'sans-serif'],
        "DMSerifDisplay": ["DM Serif Display", "serif"],
        "EbGaramond": ["EB Garamond", "serif"],
        "ElMessiri": ['El Messiri', 'sans-serif'],
        "Fahkwang": ['Fahkwang', "sans-serif"],
        "GothamBold": ["Gotham-Bold", "sans-serif"],
        "GothamBoldItalic": ["Gotham-BoldItalic", "sans-serif"],
        "GothamBook": ["Gotham-Book", "sans-serif"],
        "GothamBookItalic": ["Gotham-BookItalic", "sans-serif"],
        "GothamLight": ["Gotham-Light", "sans-serif"],
        "GothamLightItalic": ["Gotham-LightItalic", "sans-serif"],
        "Gotham": ["Gotham", "sans-serif"],
        "GothamItalic": ["Gotham-Italic", "sans-serif"],
        "Imbue": ['Imbue', 'serif'],
        "Inter": ['Inter', 'sans-serif'],
        "Jost": ['Jost', 'sans-serif'],
        "GTWalsheim": ["GTWalsheim", "serif"],
        "JuliusSansOne": ['Julius Sans One', "sans-serif"],
        "Kalam": ['Kalam', 'cursive'],
        "Kodchasan": ['Kodchasan', 'sans-serif'],
        "MajorMonoDisplay": ['Major Mono Display', 'monospace'],
        "Manrope": ['Manrope', 'sans-serif'],
        "Megrim": ["Megrim"],
        "Montserrat": ["Montserrat Subrayada", "sans-serif"],
        "MontserratAlternates" : ['Montserrat Alternates', "sans-serif"],
        "NanumMyeongjo": ["Nanum Myeongjo", "serif"],
        "NotoSerifDisplay": ["Noto Serif Display", "serif"],
        "OggLight": ['Ogg Light', 'serif'],
        "OggLightItalic": ['Ogg LightItalic', 'serif'],
        "OggMedium": ['Ogg Medium', 'serif'],
        "OggMediumItalic": ['Ogg MediumItalic', 'serif'],
        "Oswald": ['Oswald', 'sans-serif'],
        "OpenSans": ["Open Sans", "sans-serif"],
        "PermanentMarker": ['Permanent Marker', 'cursive'],
        "PetitFormal": ['Petit Formal Script', 'cursive'],
        "Philosopher" : ['Philosopher', "sans-serif"],
        "PinyonScript": ["Pinyon Script", "cursive"],
        "PlayfairDisplay": ["Playfair Display", "serif"],
        "MrsSaintDelafield": ["Mrs Saint Delafield", "cursive"],
        "PoiretOne": ["Poiret One", "sans-serif"],
        "PressStart2P": ["Press Start 2P", "cursive"],
        "Quicksand": ['Quicksand', 'sans-serif'],
        "ReemKufi": ['Reem Kufi', 'sans-serif'],
        "RubikMonoOne": ["Rubik Mono One", "sans-serif"],
        "RubikVinyl": ['Rubik Vinyl', 'cursive'],
        "Syncopate": ['Syncopate', 'sans-serif'],
        "Syne": ['Syne', 'sans-serif'],
        "TenorSans": ['Tenor Sans', 'sans-serif'],
        "Thasadith" : ['Thasadith', "sans-serif"],
        "Unbounded": ['Unbounded', 'sans-serif'],
        "WorkSans": ['Work Sans', 'sans-serif'],
      },
    },
  },
  plugins: [
    require( 'tailwindcss' ),
		require( 'autoprefixer'),
  ],
};
export default config;
